import Head from 'next/head'
import Script from 'next/script'
import InviteUserModal from '../components/common/Modal/inviteUser'
import WelcomeMessageModal from '../components/common/Modal/welcomeMessageModal'
import Header from '../components/Header'
import MainContent from '../components/MainContent'
import SideBar from '../components/SideBar'
import ActivitySidebar from '../components/SideBar/activitySidebar'
import KeyboardShortcutsSidebar from '../components/SideBar/keyboardShortcutsSidebar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <SideBar />
      <MainContent />

      <KeyboardShortcutsSidebar />

      <ActivitySidebar />

      <WelcomeMessageModal />

      <InviteUserModal />

      {/* JS Implementing Plugins  */}
      <Script src="/assets/vendor/hs-navbar-vertical-aside/hs-navbar-vertical-aside.min.js" strategy='beforeInteractive' />
      <Script src="/assets/vendor/hs-unfold/dist/hs-unfold.min.js" strategy='beforeInteractive' />
      <Script src="/assets/vendor/hs-form-search/dist/hs-form-search.min.js" strategy='beforeInteractive' />
      <Script src="/assets/vendor/select2/dist/js/select2.full.min.js" strategy='beforeInteractive' />
      <Script src="/assets/vendor/chart.js/dist/Chart.min.js" strategy='beforeInteractive' />
      <Script src="/assets/vendor/chart.js.extensions/chartjs-extensions.js" strategy='beforeInteractive' />
      <Script src="/assets/vendor/chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.min.js" strategy='beforeInteractive' />
      <Script src="/assets/vendor/daterangepicker/moment.min.js" strategy='beforeInteractive' />
      <Script src="/assets/vendor/daterangepicker/daterangepicker.js" strategy='beforeInteractive' />
      <Script src="/assets/vendor/datatables/media/js/jquery.dataTables.min.js" strategy='beforeInteractive' />
      <Script src="/assets/vendor/datatables.net.extensions/select/select.min.js" strategy='beforeInteractive' />
      <Script src="/assets/vendor/clipboard/dist/clipboard.min.js" strategy='beforeInteractive' />


      {/* JS Front */}
      <Script src="/assets/js/theme.min.js" />
      {/* JS Plugins Init */}
      <Script src="/assets/js/js-plugins_init.js" strategy='lazyOnload' />
      {/* IE Support */}
      <Script src='/assets/js/ie-support.js' />


    </>
  )
}
